# Generated by Django 5.2.3 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='Class',
        ),
        migrations.AddField(
            model_name='student_model',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='name',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
