# Generated by Django 5.2.3 on 2025-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_model_class_student_model_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=True, max_length=100)),
                ('product_origin', models.CharField(max_length=50, null=True)),
                ('product_date', models.DateTimeField()),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
