# Generated by Django 5.2.3 on 2025-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.CharField(),
        ),
    ]
