# Generated by Django 5.2.3 on 2025-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_product_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
