# Generated by Django 5.2.4 on 2025-07-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_product_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_date',
            new_name='productdate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_origin',
            new_name='productorigin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='productprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='producttype',
        ),
    ]
