# Generated by Django 5.2.4 on 2025-07-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_rename_product_date_product_productdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
