# Generated by Django 5.2.4 on 2025-07-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
