# Generated by Django 5.2.4 on 2025-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_alter_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productorigin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producttype',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
