# Generated by Django 5.2.4 on 2025-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_null_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
