# Generated by Django 5.2.4 on 2025-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_product_for_null_value_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_null_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
