# Generated by Django 5.2.4 on 2025-08-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_alter_product_for_null_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_null_value',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
