# Generated by Django 5.2.4 on 2025-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
