# Generated by Django 5.2.4 on 2025-08-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Untitled', max_length=100, null=True),
        ),
    ]
