# Generated by Django 5.2.4 on 2025-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0029_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(),
        ),
    ]
