# Generated by Django 5.2.4 on 2025-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0034_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Null_name', max_length=100),
            preserve_default=False,
        ),
    ]
