# Generated by Django 5.2.4 on 2025-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0037_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='untitled', max_length=250, null=True),
        ),
    ]
