# Generated by Django 5.2.4 on 2025-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0039_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='king', max_length=250),
            preserve_default=False,
        ),
    ]
