# Generated by Django 5.2.4 on 2025-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0041_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
