# Generated by Django 5.2.3 on 2025-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_naughty',
            field=models.BooleanField(default=True),
        ),
    ]
