# Generated by Django 5.2.3 on 2025-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_naughty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.CharField(null=True),
        ),
    ]
