# Generated by Django 5.2.3 on 2025-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_is_naughty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('model', models.CharField()),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
                ('origin', models.CharField()),
            ],
        ),
    ]
