# Generated by Django 5.2.3 on 2025-07-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='carname',
        ),
    ]
